### This configuration defines the parameters the program will use to ensure rule compliance
#   Assume values are in inches unless otherwise specified, or no unit is needed
#
#! IMPORTANT !! 
#! Ensure these values match those defined by the current rulebook
#!
#! All values must be floating point values in order to be parsed

[user]
firewall_angle=18.0  # angle of firewall from vertical
seat_height=0.0
sim_height=0.0

[clearance]
head=6.0  # clearance required from the head/helmet
body=3.0  # clearance required from the body

[rules]
lateral=8.0    # minimum length of lateral members
vertical=42.0  # minimum height from the seat bottom to the roll hoop overhead member

[process]
iteration_step=0.01   # step used by optimizer, smaller number is more accurate but will increase compute time exponentially
output="data/chassis.pts"  # path for the finalized points file
