#!/usr/bin/env sh
set -e

if [ ! -d "build" ]; then
    mkdir -p /workspace/build/debug
    mkdir -p /workspace/build/release
fi

cmake -S /workspace -B /workspace/build/debug -DCMAKE_BUILD_TYPE=Debug
cmake --build /workspace/build/debug

echo "Build complete"
