# syntax=docker/dockerfile:1.7
FROM nixos/nix:2.26.4

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

COPY packer/default.nix /env/default.nix
COPY packer/build /env/build

RUN chmod +x /env/build
RUN nix-shell --pure /env/default.nix --run "echo DOCKER_NIX_IMAGE"

WORKDIR /workspace
