name: Require CHANGELOG and VERSION Modification

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Check for target branch
        run: |
          # Ensure this workflow only runs for 'main' as a status check
          if [ "${{ github.base_ref }}" != "main" ]; then
            echo "This workflow only runs for status checks on the 'main' branch."
            exit 0
          fi

      - name: Check for CHANGELOG and VERSION
        run: |
          if ! git diff --name-only origin/main...HEAD | grep -q "CHANGELOG.md"; then
            echo "Must add to the CHANGELOG"
            exit 1
          fi

          if ! git diff --name-only origin/main...HEAD | grep -q "VERSION"; then
            echo "Must iterate the VERSION"
            exit 1
          fi
