name: Require CHANGELOG and VERSION Modification

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize, reopened]

# on:
#   pull_request:
#     branches:
#       - main
#     types: [opened, edited, synchronize]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for CHANGELOG and VERSION
        run: |
          git fetch origin main
          if ! git diff --name-only origin/main | grep -q "CHANGELOG.md"; then
            echo "Must add to the CHANGELOG"
            exit 1
          fi

          if ! git diff --name-only origin/main | grep -q "VERSION"; then
            echo "Must iterate the VERSION"
            exit 1
          fi
